uk:
  domain: .mgnonprod.co.uk/
  sub: www-

us:
  domain: .mgnonprod.co.uk/
  sub: www-us-

fr:
  domain: .mgnonprod.co.uk/
  sub: www-fr-

au:
  domain: .mgnonprod.co.uk/
  sub: www-au-

es:
  domain: .mgnonprod.co.uk/es/
  sub: www-

de:
  domain: .mgnonprod.co.uk/de/
  sub: www-

eu:
  eu_domain: .mgnonprod.co.uk/
  sub: www-eu-

admin:
  admin: .mgnonprod.co.uk/index.php/adminV6yozjEQBynz/
  sub: admin-
